version: 2

updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "03:00"
      timezone: "UTC"
    reviewers:
      - "djunekz"
    assignees:
      - "djunekz"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "deps(actions)"
